# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Nospresso' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nospresso
  pod 'SnapKit', '~> 5.6.0'

  target 'NospressoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NospressoUITests' do
    # Pods for testing
  end

end
