# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubRepositories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubRepositories
  pod 'SnapKit', '~> 5.6.0'
  pod 'R.swift'
  pod 'Nuke'

  target 'GithubRepositoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubRepositoriesUITests' do
    # Pods for testing
  end

end
